---
title: "LC VCO mit einem Colpitts Oszillator"
format: html
---

# Kunden Anforderungen
- 5,5 MHz Mittenfrequenz (Zwischenfrequenz Fernseher)
- Eingang 0 V
- linear ± 0,5 V ≙ ± 0,5 MHz
- Bandbreite von 5 bis 6 MHz
- nicht lineare Verzerrung sehr klein
- Robuste Platine für anschaulichen Unterricht
- große Bauteile
- Spannungsteiler integriert
- Ein- und Ausgang BNC
- Ausgangswiderstand 50 Ω
- Frequenzdrift durch Gleichspannung korrigiert
- Kennlinienermittlung mit Gleichspannung
- Kurzschluss sicher

## Quellen für den Colpitts Oszillator
- [Elektroniktutor FM Modulation](https://www.elektroniktutor.de/signalkunde/fm.html)
- [Elektroniktutor Colpitts Oszillator](https://www.elektroniktutor.de/signalkunde/colpitts.html)

### Coilpitts Oszillator in Emitterschaltung für 125 kHz

Als erstes haben wir den Colpitts Oszillator für für 125 kHz von der Elektroniktutor
Seite in KiCad und danach auf einer Platine aufgebaut.

[Schaltplan als PDF](/ANS-Projekt/Messungen/Schemata/Colpitts_Oszillator.pdf)

#### Colpitts Oszillator in Basisschaltung für 5,5 MHz

